// courses
export const REQUEST_COURSES = "REQUEST_COURSES";
export const RECEIVE_COURSES_SUCCESS = "RECEIVE_COURSES_SUCCESS";
export const RECEIVE_COURSES_ERROR = "RECEIVE_COURSES_ERROR";
export const REFRESH_COURSES = "REFRESH_COURSES";

// add course
export const ADD_USER_DATA = "ADD_USER_DATA";
export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const EDIT_USER_DATA = "EDIT_USER_DATA";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const FINISH_EDIT_USER_DATA = "FINISH_EDIT_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

// user data
export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const RECEIVE_USER_DATA_SUCCESS = "RECEIVE_USER_DATA_SUCCESS";
export const RECEIVE_USER_DATA_ERROR = "RECEIVE_USER_DATA_ERROR";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

// auth
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOG_OUT = "LOG_OUT";

// flash messages
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const CLOSE_FLASH_MESSAGE = "CLOSE_FLASH_MESSAGE";

// modal
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
